services:
  mysql:
    build:
      context: .
      dockerfile: db/Dockerfile  
    image: bookshop-db
    ports:
     - "3306" 
    volumes:
     - bookshop-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_DATABASE: bookshop
    networks:
     - app-network

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile  
      secrets:
       - git_pat    
    image: bookshop-apache
    ports:
     - "8000" 
    networks:
     - app-network
       
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  
      secrets:   
       - git_pat
    image: bookshop-app
    ports:
     - "3000"
    networks:
     - app-network 
    depends_on:
     - mysql
     - apache   

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - apache
    networks:
      - app-network

volumes:
   bookshop-db-data: {}

secrets:
  git_pat:
    file: ./.git-token

networks:
  app-network:
    driver: bridge
       
