apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
 labels: 
    deployment: frontend-deployment
spec:
 selector:
   matchLabels:
     app: frontend
 replicas: 1
 template: 
    metadata:
     labels: 
      app: frontend
    spec:
     containers: 
      - name: frontend
        image: 315071206125.dkr.ecr.us-east-1.amazonaws.com/bookshop/frontend:v1
        ports:
         - name: front-end-port
           containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
