apiVersion: apps/v1
kind: Deployment
metadata:
 name: apache-deployment
 labels:
   deployment: apache-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
    app: apache
 template:
   metadata:
    labels:
      app: apache
   spec:
     containers:
     - name: apache
       image: 315071206125.dkr.ecr.us-east-1.amazonaws.com/bookshop/apache:v1
       ports:
       - name: apache-port  
         containerPort: 8000
       resources:
         requests:
           memory: "128Mi"
           cpu: "100m"
         limits:
           memory: "256Mi"
           cpu: "200m"
       tolerations:
        - key: "backend-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"